### PR TITLE
fix: stop submit if the sum of score isn't 100

### PR DESCRIPTION
**Pull request by laporchen**
Add some checks on `edit.vue` and `new.vue` to prevent invalid task score being submitted.

### CODE REVIEW

**Review by uier — APPROVED** [review]
Thank you for your contribution.

It looks good to me, however, we've setup a form validation in `ProblemForm.vue`, would be great to integrate this limitation into form rules.

What do you think? It's okay to merge this now for deploying the patches earlier, but I would suggest to open an issue to address this in the future.

**Comment by laporchen** [comment]
I think I can change it to vuelidate, but I need to take a look at the custom validator part.

**Comment by laporchen** [comment]
I update it to use vuelidate now.

**Review by uier — APPROVED** [review]
lgtm

**Pull request merged**
